language: node_js
node_js:
 - '6'

before_install:
  - npm install -g typings@1.3.2 && npm install -g gulp

script:
  - "gulp"

after_script:
  - "istanbul cover jasmine-node --captureExceptions build/test -e ./coverage/lcov.info && npm install coveralls@2 ./coverage/coverage.json -t lcovonly | coveralls"
